

/*The null hypothesis is that the
    variable contains a unit root, 
	and the alternative is that the variable 
	was generated by a stationary process.*/

// Toda-Yamamoto procedure for causality

//1. Integration order
varsoc fbcf, max(6)
dfuller fbcf, trend lags(4) // there is a unit root

varsoc D.fbcf, max(6)
dfuller D.fbcf, trend lags(6) // there is no unit root => I(1)

varsoc lagr, max(6) 
dfuller lagr, trend lags(5) // there is a unit root

varsoc D.lagr, max(6)
dfuller D.lagr, trend lags(6) // there is no unit root => I(1)

varsoc lcom, max(6) 
dfuller lcom, trend lags(4) // there is a unit root

varsoc D.lcom, max(6)
dfuller D.lcom, trend lags(3) // there is no unit root => I(1)

varsoc lind, max(6)
dfuller lind, trend lags(4) // there is a unit root

varsoc D.lind, max(6)
dfuller D.lind, trend lags(4) // there is no unit root => I(1)

varsoc linf, max(6) 
dfuller linf, trend lags(5) // there is a unit root 

varsoc D.linf, max(6)
dfuller D.linf, trend lags(4) // there is no unit root => I(1)

varsoc ltot, max(6) 
dfuller ltot, trend lags(5) // there is a unit root 

varsoc D.ltot, max(6)
dfuller D.ltot, trend lags(4) // there is no unit root => I(1)

varsoc wp, max(6)
dfuller wp, trend lags(3) // there is a unit root 

varsoc D.wp, max(6)
dfuller D.wp, trend lags(2) // there is no unit root => I(1)

varsoc tt, max(6)
dfuller tt, trend lags(3) // there is a unit root 

varsoc D.tt, max(6)
dfuller D.tt, trend lags(2) // there is no unit root => I(1)

varsoc wp, max(6)
dfuller wp, trend lags(3) // there is no  unit root 

//2. m' = 1 (fbcf and lagr are I(1))

//3. VAR lag length:
varsoc fbcf lagr lcom lind linf ltot, max(10)

//4. test for serial correlation
quiet var fbcf lagr lcom lind linf ltot, lags(1/4)
varlmar

//5. 5 lags = > p + m = 5
quiet var fbcf lagr lcom lind linf ltot, lags(1/5)

//******************************************************************************
// TT and WP
//3. VAR lag length:
varsoc fbcf wp tt, max(10)
//p=3

//4. test for serial correlation
quiet var fbcf wp tt, lags(1/3)
varlmar

//5. 5 lags = > p + m = 4
quiet var fbcf wp tt, lags(1/4)


// Causality
* test for fbcf Granger–causality to wp
test [wp]L.fbcf [wp]L2.fbcf [wp]L3.fbcf [wp]L4.fbcf

* test for wp Granger–causality to fbcf
test [fbcf]L.wp [fbcf]L2.wp [fbcf]L3.wp [fbcf]L4.wp

// Causality
* test for fbcf Granger–causality to tt
test [tt]L.fbcf [tt]L2.fbcf [tt]L3.fbcf [tt]L4.fbcf

* test for tt Granger–causality to fbcf
test [fbcf]L.tt [fbcf]L2.tt [fbcf]L3.tt [fbcf]L4.tt



//varsoc fbcf wp, max(15)
//quiet var D.fbcf D.wp, lags(1/6)
//varlmar
//var fbcf wp, lags(1/10)
//vargranger

//test [wp]L.fbcf [wp]L2.fbcf [wp]L3.fbcf [wp]L4.fbcf

* test for wp Granger–causality to fbcf
//test [fbcf]L.wp [fbcf]L2.wp [fbcf]L3.wp [fbcf]L4.wp

**********************************************************

* test for fbcf Granger–causality to lagr
//test [lagr]L.fbcf [lagr]L2.fbcf [lagr]L3.fbcf [lagr]L4.fbcf [lagr]L5.fbcf

* test for lagr Granger–causality to fbcf
//test [fbcf]L.lagr [fbcf]L2.lagr [fbcf]L3.lagr [fbcf]L4.lagr [fbcf]L5.lagr

**********************************************************

* test for fbcf Granger–causality to lind
//test [lind]L.fbcf [lind]L2.fbcf [lind]L3.fbcf [lind]L4.fbcf [lind]L5.fbcf

* test for lind Granger–causality to fbcf
//test [fbcf]L.lind [fbcf]L2.lind [fbcf]L3.lind [fbcf]L4.lind  [fbcf]L5.lind  

**********************************************************
* test for fbcf Granger–causality to linf
//test [linf]L.fbcf [linf]L2.fbcf [linf]L3.fbcf [linf]L4.fbcf [linf]L5.fbcf

* test for lind Granger–causality to fbcf
//test [fbcf]L.linf [fbcf]L2.linf [fbcf]L3.linf [fbcf]L4.linf [fbcf]L5.linf

**********************************************************
* test for fbcf Granger–causality to lcom
//test [lcom]L.fbcf [lcom]L2.fbcf [lcom]L3.fbcf [lcom]L4.fbcf [lcom]L5.fbcf

* test for lind Granger–causality to fbcf
//test [fbcf]L.lcom [fbcf]L2.lcom [fbcf]L3.lcom [fbcf]L4.lcom [fbcf]L5.lcom

**********************************************************
* test for fbcf Granger–causality to ltot
//test [ltot]L.fbcf [ltot]L2.fbcf [ltot]L3.fbcf [ltot]L4.fbcf [ltot]L5.fbcf

* test for ltot Granger–causality to fbcf
//test [fbcf]L.ltot [fbcf]L2.ltot [fbcf]L3.ltot [fbcf]L4.ltot [fbcf]L5.ltot


/* não há causalidade no sentido Granger em qualquer direção entre
fbcf e qualquer dos desembolsos do BNDES*/